---
apiVersion: v1
kind: Pod
metadata:
  name: mypod-1
spec:
  containers:
    - name: cont1
      image: nginx
      ports:
        - containerPort: 80
      envFrom:
        - secretRef:
             name: mysec
